# vim ft=yaml
# CI on Windows via appveyor

environment:
  global:
    MSYS2_ROOT: c:\msys64
    WHEELHOUSE_UPLOADER_USERNAME: travis-worker
    WHEELHOUSE_UPLOADER_SECRET:
      secure: 9s0gdDGnNnTt7hvyNpn0/ZzOMGPdwPp2SewFTfGzYk7uI+rdAN9rFq2D1gAP4NQh

  matrix:
    - BITS: 64
    - BITS: 32

build_script:
    - if "%BUILD_BITS%"=="32" (set PLAT=i686) else (set PLAT=x86_64)
    - PATH=%MSYS2_ROOT%\usr\bin;%PATH%
    # Remove competing gcc / gfortran
    - pacman -Rs --noconfirm gcc gcc-fortran mingw-w64-%PLAT%-toolchain
    # zip needed for packing archive
    - pacman -Sy --noconfirm zip
    - git submodule update --init --recursive
    - set MSYSTEM=MINGW%BUILD_BITS%
    - set START_DIR=%__CD__%
      # Need --login to process MSYSTEM variable
    - bash --login %START_DIR%build_mingwpy.sh

on_finish:
  # Note the resulting IP:port address, and use in Microsoft Remote Desktop
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
