# vim ft=yaml
# CI on Windows via appveyor

branches:
  except:
    - /.*azure.*/

environment:
  global:
    MSYS2_ROOT: c:\msys64
    GCC_VER: 8.2.0
    REV_NO: 201812
    WHEELHOUSE_UPLOADER_USERNAME: travis-worker
    WHEELHOUSE_UPLOADER_SECRET:
      secure: 9s0gdDGnNnTt7hvyNpn0/ZzOMGPdwPp2SewFTfGzYk7uI+rdAN9rFq2D1gAP4NQh

  matrix:
    - BITS: 64
    - BITS: 32

build_script:
    - PATH=%MSYS2_ROOT%\usr\bin;%PATH%
    # zip needed for packing archive
    - pacman -Sy --noconfirm zip
    - git submodule update --init --recursive
    - set MSYSTEM=MINGW%BUILD_BITS%
    # START_DIR tells build script where to find this directory
    - set START_DIR=%__CD__%
      # Need --login to process MSYSTEM variable
    - bash --login %START_DIR%build_mingwpy.sh

artifacts:
  - path: build\*.*
