# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

jobs:
- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  strategy:
    maxParallel: 10
    matrix:
      x64:
        ARCH: 'x64'
      x86:
        ARCH: 'x86'
  steps:
  - script: |
      rem We'll see
      dir c:\
  - script: |
      rem Get 7zip
      choco install 7zip.install
      xz --help
  - powershell: |
      # Maybe
      ls c:\
