# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

jobs:
- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  strategy:
    maxParallel: 10
    matrix:
      x64:
        ARCH: 'x64'
      x86:
        ARCH: 'x86'
  steps:
  - script: |
      rem We'll see
      dir c:\
  - script: |
      rem Get, run msys2 bash
      choco install 7zip.install
      choco install curl
      curl -L http://repo.msys2.org/distrib/x86_64/msys2-base-x86_64-20181211.tar.xz -o msys2.tar.xz
      7z x msys2.tar.xz
      7z x msys2.tar
      PATH=%__CD__%\msys64\usr\bin;%PATH%
      bash -c 'echo In Bash from cmd'
    workingDirectory: C:\Temp

  - powershell: |
      # Maybe
      bash -c 'echo In Bash from powershell'
