# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
  GCC_VER: 5.3.0
  REV_NO: 201812
  N_THREADS: 8

jobs:
- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  strategy:
    maxParallel: 10
    matrix:
      64:
        BITS: 64
  timeoutInMinutes: 360
  steps:
  - script: |
      :: Get msys2 bash
      choco install 7zip.install
      choco install curl
      curl -L http://repo.msys2.org/distrib/x86_64/msys2-base-x86_64-20181211.tar.xz -o msys2.tar.xz
      7z x msys2.tar.xz
      7z x msys2.tar
      :: See: https://stackoverflow.com/questions/52631143/cannot-change-the-path-in-a-script-task-in-azure-pipelines
      ECHO ##vso[task.prependpath]%__CD__%\msys64\usr\bin
    workingDirectory: C:\Temp
    displayName: 'Get msys2'

  - script: |
      :: Run build_mingwpy script
      git submodule update --init --recursive
      set MSYSTEM=MINGW%BITS%
      :: START_DIR tells build script where to find this directory
      set START_DIR=%__CD__%
      :: Need --login to process MSYSTEM variable
      bash --login -c 'echo First login'
      bash --login %START_DIR%build_mingwpy.sh
    displayName: 'Build mingwpy'

  - script: |
      dir build
