# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

jobs:
- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  strategy:
    maxParallel: 10
    matrix:
      64:
        BITS: 64
  steps:
  - script: |
      rem List current directory
      dir
  - script: |
      rem Get, run msys2 bash
      choco install 7zip.install
      choco install curl
      curl -L http://repo.msys2.org/distrib/x86_64/msys2-base-x86_64-20181211.tar.xz -o msys2.tar.xz
      7z x msys2.tar.xz
      7z x msys2.tar
      rem See: https://stackoverflow.com/questions/52631143/cannot-change-the-path-in-a-script-task-in-azure-pipelines
      ECHO ##vso[task.prependpath]%__CD__%\msys64\usr\bin
      bash -c 'echo In Bash from cmd'
    workingDirectory: C:\Temp

  - script: |
      PATH
      where bash
      bash --login -c 'echo First login'
      bash --login -c 'echo $PATH'
      bash --login -c 'pacman'

  - script: |
      rem Run build_mingpy script
      set GCC_VER=8.2.0
      set REV_NO=201812
      git submodule update --init --recursive
      set MSYSTEM=MINGW%BITS%
      rem START_DIR tells build script where to find this directory
      set START_DIR=%__CD__%
      rem Need --login to process MSYSTEM variable
      bash --login %START_DIR%build_mingwpy.sh
